using System.Text;

namespace ReDows.Core.Apps;

/// <summary>
/// Result of emitting an InDows winget catalog from the app inventory: the YAML
/// text plus the curation counts — active entries are live, candidates and manual
/// apps are emitted as comments to review.
/// </summary>
public sealed record InDowsCatalog(string Yaml, int ActiveCount, int CandidateCount, int ManualCount);

/// <summary>
/// Emits an InDows-ready <c>configuration.dsc.yaml</c> (winget DSC catalog) from the
/// installed-apps inventory — the apps half of the ReDows → InDows hand-off (M2).
/// Conservative curation: only exact winget correlations become live entries; an
/// uncertain match or an app with no winget id is listed as a comment to review
/// (a wrong reinstall id is worse than none). Commented lines deliberately never
/// carry the live <c>source: winget</c> pattern, so an InDows line-based reader
/// cannot install them by accident. Pure and deterministic (no timestamp) so it is
/// testable on fixtures; the entry line matches the exact shape InDows reads.
/// </summary>
public static class InDowsCatalogEmitter
{
    private const string WinGetSource = "winget";
    private const string WinGetResource = "Microsoft.WinGet.DSC/WinGetPackage";

    public static InDowsCatalog Emit(IReadOnlyList<AppEntry> entries)
    {
        var apps = entries.Where(e => e.Kind == AppEntryKind.App).ToList();

        var active = DistinctWinGetIds(apps, ReinstallConfidence.Exact);
        var inActive = new HashSet<string>(active, StringComparer.OrdinalIgnoreCase);

        var candidates = DistinctWinGetIds(apps, ReinstallConfidence.Candidate)
            .Where(id => !inActive.Contains(id))
            .ToList();

        // Apps whose record carries no winget id (no reinstall hint, or a non-winget
        // one such as choco/scoop): can't be a winget entry, so listed by name to be
        // reviewed — nothing is silently dropped. Deduped by label.
        var manual = apps
            .Where(e => e.Reinstall is null || !IsWinGet(e.Reinstall))
            .Select(ManualLabel)
            .Where(label => label.Length > 0)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(label => label, StringComparer.OrdinalIgnoreCase)
            .ToList();

        return new InDowsCatalog(Render(active, candidates, manual), active.Count, candidates.Count, manual.Count);
    }

    private static List<string> DistinctWinGetIds(IEnumerable<AppEntry> apps, ReinstallConfidence confidence) =>
        apps
            .Select(e => e.Reinstall)
            .OfType<ReinstallHint>()
            .Where(r => IsWinGet(r) && r.Confidence == confidence)
            .Select(r => r.Id)
            .Where(id => !string.IsNullOrWhiteSpace(id))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(id => id, StringComparer.OrdinalIgnoreCase)
            .ToList();

    private static bool IsWinGet(ReinstallHint hint) =>
        string.Equals(hint.Kind, WinGetSource, StringComparison.OrdinalIgnoreCase);

    private static string ManualLabel(AppEntry entry)
    {
        var name = (entry.Name ?? string.Empty).Trim();
        if (name.Length == 0)
        {
            return string.Empty;
        }

        // Surface a non-winget reinstall path (choco/scoop/…) if the inventory found one.
        return entry.Reinstall is { } r ? $"{name} ({r.Kind}:{r.Id})" : name;
    }

    private static string Render(IReadOnlyList<string> active, IReadOnlyList<string> candidates, IReadOnlyList<string> manual)
    {
        var text = new StringBuilder();

        text.Append("# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2\n");
        text.Append("#\n");
        text.Append("# configuration.dsc.yaml — generated by ReDows from the installed-apps inventory.\n");
        text.Append("# Drop this file into InDows to reinstall these apps via winget at first logon.\n");
        text.Append("#\n");
        text.Append($"# {active.Count} app(s) with a confirmed winget id are listed below (active).\n");
        text.Append($"# {candidates.Count} uncertain match(es) and {manual.Count} app(s) without a winget id\n");
        text.Append("# follow as comments to review: a wrong reinstall id is worse than none.\n");
        text.Append("#\n");
        text.Append("properties:\n");
        text.Append("  configurationVersion: 0.2.0\n");
        text.Append("  resources:\n");

        foreach (var id in active)
        {
            text.Append(Entry(id)).Append('\n');
        }

        if (candidates.Count > 0)
        {
            text.Append('\n');
            text.Append("    # Uncertain winget matches — verify each id, then add it above as an entry:\n");
            foreach (var id in candidates)
            {
                text.Append("    #   ").Append(id).Append('\n');
            }
        }

        if (manual.Count > 0)
        {
            text.Append('\n');
            text.Append("    # No winget id found — install manually or find an id (nothing dropped):\n");
            foreach (var label in manual)
            {
                text.Append("    #   ").Append(label).Append('\n');
            }
        }

        return text.ToString();
    }

    private static string Entry(string id) =>
        $"    - {{ resource: {WinGetResource}, id: {id}, settings: {{ id: {id}, source: {WinGetSource} }} }}";
}
